networks:
  pickside-network:
    external: true

services:
  authsvc:
    build: .
    container_name: authsvc
    ports:
      - "8081:8081"
    networks:
      - pickside-network
    environment:
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_TOKEN=${VAULT_TOKEN}